PRIMER_DICT = {
    'A': 'T',
    'T': 'A',
    'C': 'G',
    'G': 'C',
    'B': '[GCA]',
    'D': '[TCA]',
    'H': '[TGA]',
    'K': '(C|A)',
    'M': '(T|G)',
    'N': '\\w',
    'R': '(T|C)',
    'S': '(G|C)',
    'V': '[TGC]',
    'W': '(T|A)',
    'Y': '(G|A)',
}