PRIMER_DICT = {
    'A': 'T',
    'T': 'A',
    'C': 'G',
    'G': 'C',
    'B': '[GCA]',
    'D': '[TCA]',
    'H': '[TGA]',
    'K': '[CA]',
    'M': '[TG]',
    'R': '[TC]',
    'S': '[GC]',
    'V': '[TGC]',
    'W': '[TA]',
    'Y': '[GA]',
}