PRIMER_DICT1 = {
    'A': 'T',
    'T': 'A',
    'C': 'G',
    'G': 'C',
    'B': '[GCA]',
    'D': '[TCA]',
    'H': '[TGA]',
    'K': '[CA]',
    'M': '[TG]',
    'R': '[TC]',
    'S': '[GC]',
    'V': '[TGC]',
    'W': '[TA]',
    'Y': '[GA]',
}

PRIMER_DICT2 = {
    'A': 'A',
    'T': 'T',
    'C': 'C',
    'G': 'G',
    'B': '[CGT]',
    'D': '[AGT]',
    'H': '[ACT]',
    'K': '[GT]',
    'M': '[AC]',
    'R': '[AG]',
    'S': '[CG]',
    'V': '[ACG]',
    'W': '[AT]',
    'Y': '[CT]',
}